version: "3.8"

services:
  app:
    build:
      context: .
      target: prod
    ports:
      - "3001:3060"
    environment:
      - PORT=3060
      - DATABASE_URL=postgresql://postgres:Gamcb2025@db:5432/dashboard
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Gamcb2025
      - POSTGRES_DB=dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
